/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function plus100(input: number): number
export interface Modifiers {
  lshift?: boolean
  rshift?: boolean
  lctrl?: boolean
  rctrl?: boolean
  lalt?: boolean
  meta?: boolean
}
export declare function pressKey(key: string, modifiers?: Modifiers | undefined | null): string
export declare function sendText(text: string): void
